# Generated by Django 3.2.5 on 2021-07-22 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Deal', max_length=100)),
                ('investment', models.CharField(choices=[('BTCUSDC', 'BTCUSDC'), ('ETHUSDC', 'ETHUSDC'), ('BTCETH', 'BTCETH'), ('LINK', 'CHAINLINK'), ('BTC', 'BITCOIN'), ('ETH', 'ETHEREUM'), ('AAVE', 'AAVE'), ('ADA', 'CARDANO'), ('DOT', 'POLKADOT'), ('LTC', 'LITECOIN'), ('USDT', 'TETHER'), ('BNB', 'BINANCE COIN'), ('FIL', 'FILECOIN'), ('DOGE', 'DOGECOIN'), ('TRX', 'TRON'), ('USDC', 'USD COIN')], default='BTC', max_length=10)),
                ('indicators', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('operation', models.CharField(choices=[('Buy', 'BUY'), ('Sell', 'SEL')], default='BUY', max_length=10)),
                ('entry_price', models.CharField(choices=[('Price', 'PRC'), ('Auto', 'AUT')], default='AUT', max_length=10)),
                ('stop_gain', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('strategy', models.CharField(choices=[('None', 'STF'), ('Strategy', 'STT')], default='STF', max_length=10)),
                ('visibility', models.CharField(choices=[('Public', 'VST'), ('Private', 'VSF')], default='VST', max_length=10)),
                ('contribuitors', models.IntegerField(default=1)),
                ('amount', models.FloatField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('execution', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
